version: 0.0
environment_variables:
    plaintext:
        "INPUT_FILE": ""
        "S3_WEBSITE_BUCKET": ""
        "S3_ARTIFACT_BUCKET": ""
containers:
    LambdaFunctions:
        phases:
            during_build:
                commands:
                    - npm install
               
                    - npm install --save-dev mocha
                    - npm install --save-dev should
                    - npm install --save-dev supertest
                    - npm install chai
                    - npm install assert
                    - npm install simple-mock
                    - 
                    - aws cloudformation package --template-file samTemplate.yaml --s3-bucket $S3_BUCKET  --output-template-file sam-template-output.yaml
     
                   
        artifacts:
            files:
                - sam-template-output.yaml